# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-24 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretaed_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(b'Accepted', b'Accepted'), (b'Denied', b'Denied'), (b'Pending', b'Pending'), (b'Self', b'Self'), (b'Uknown', b'Uknown')], max_length=30)),
                ('permisssion', models.CharField(choices=[(b'Admin', b'Admin'), (b'Read', b'Read'), (b'Restricted', b'Restricted'), (b'Write', b'Write')], max_length=30)),
            ],
            options={
                'db_table': 'challenge_host',
            },
        ),
        migrations.CreateModel(
            name='ChallengeHostTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretaed_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_host_team_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_host_team',
            },
        ),
        migrations.AddField(
            model_name='challengehost',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.ChallengeHostTeam'),
        ),
        migrations.AddField(
            model_name='challengehost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
