# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-25 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengehost',
            old_name='permisssion',
            new_name='permissions',
        ),
    ]
