# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cretaed_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('terms_nd_conditions', models.TextField(blank=True, null=True)),
                ('submission_guidelines', models.TextField(blank=True, null=True)),
                ('evaluation_details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'logos', verbose_name=b'Logo')),
                ('published', models.BooleanField(default=False, verbose_name=b'Publicly Available')),
                ('enable_form', models.BooleanField(default=False)),
                ('anonymous_leaderboard', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'challenge',
            },
        ),
    ]
